image: maven:3.9.6-eclipse-temurin-21

stages:
  - git
  - test
  - build
  - publish

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.test.failure.ignore=false"

git:
  stage: git
  script:
    - git --version

test:
  stage: test
  script:
    - java --version
    - mvn $MAVEN_CLI_OPTS test

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

publish-artifact:
  stage: publish
  script:
    - BUILD_TAG="build-$(date +'%Y-%m-%d_%H-%M')"
    - echo "$BUILD_TAG"
    - mvn $MAVEN_CLI_OPTS clean package
    - mkdir -p artifacts
    - cp target/*.jar artifacts/myapp-${BUILD_TAG}.jar
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
