image: maven:3.9.6-eclipse-temurin-21

stages:
  - git
  - test
  - build
  - sonar
  - publish

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.test.failure.ignore=false"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

git:
  stage: git
  script:
    - git --version

test:
  stage: test
  script:
    - java --version
    - mvn $MAVEN_CLI_OPTS test

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

sonar-analysis:
  stage: sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
  script:
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH != 'main'

publish-artifact:
  stage: publish
  script:
    - BUILD_TAG="build-$(date +'%Y-%m-%d_%H-%M')"
    - echo "$BUILD_TAG"
    - mvn $MAVEN_CLI_OPTS clean package
    - mkdir -p artifacts
    - cp target/*.jar artifacts/myapp-${BUILD_TAG}.jar
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success